*Contenuti*
===
- [Scikit-learn: machine learning con Python](#Scikit-learn:-machine-learning-con-Python)
- [Un modello per la classificazione](#Un-modello-per-la-classificazione)

Scikit-learn: machine learning con Python
===

*Scikit-learn* (o *sklearn*) è uno dei principali strumenti Python per il machine learning ed è la libreria open-source di data science più usata al mondo.

Sulla pagina di sklearn, http://scikit-learn.org/stable/, si trovano svariati modelli di machine learning, insieme a strumenti di preprocessing, analisi e visualizzazione dei dati. 

Ciascuna implementazione fa riferimento ad una guida utente molto dettagliata, che associa al codice la teoria necessaria per capirlo ed usarlo:

http://scikit-learn.org/stable/modules/classes.html.

Oltre a permettere di *usare* il machine learning scrivendo pochissime righe di codice, la libreria è altamente modulare, e dà la possibilità agli utenti di costruire la propria implementazione basandosi su metodi, oggetti ed interfacce esistenti.

Teoria e codice sono spesso supportati da esempi pratici di utilizzo, affiancati da analisi grafiche: http://scikit-learn.org/stable/auto_examples/.

Un modello per la classificazione
---
Costruiamo un modello $K$-nearest neighbors (KNN) per la classificazione, utilizzando l'implementazione sklearn *KNeighborsClassifier*.

In [6]:
from sklearn import neighbors

print(neighbors)

<module 'sklearn.neighbors' from '/home/francesco/anaconda3/lib/python3.6/site-packages/sklearn/neighbors/__init__.py'>


*neighbors* è un *modulo*, ovvero insiemi di oggetti e funzioni con caratteristiche comuni, impacchettati insieme.

Se scriviamo

                neighbors.
                
e premiamo il tasto di autocomplemento possiamo dare un'occhiata agli oggetti contenuti nel modulo. Tra gli altri, vedremo KNeighborsClassifier.

In [7]:
model = neighbors.KNeighborsClassifier()
print(model)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')


Abbiamo chiamato un metodo speciale, chiamato *costrutture*, che inizializza (senza parametri) un oggetto di tipo KNeighborsClassifier. Possiamo vedere

- dalla documentazione: http://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html
- posizionando il puntatore del mouse dentro le parentesi del costruttore e premendo Shift e due volte Tab
- stampando l'oggetto creato,

che questa implementazione del classificatore KNN prende in ingresso diversi parametri, nessuno dei quali obbligatorio. Per esempio, il numero di vicini $k$ (chiamato *n_neighbors*) vale di default 5.

In [26]:
model = neighbors.KNeighborsClassifier(n_neighbors=3)
print(model)
print('k:', model.n_neighbors)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')
k: 3


Attraverso il modulo *datasets*, sklearn mette a disposizione diversi dataset, sui quali fare apprendimento e testare un modello.

In [9]:
from sklearn import datasets

iris = datasets.load_iris()
print(type(iris))

<class 'sklearn.utils.Bunch'>


Il tipo *Bunch* è molto simile a un dizionario. Oltre alla matrice delle feature e al vettore delle etichette, troviamo anche qualche informazione sul dataset.

In [10]:
print(iris.keys())

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])


In [11]:
print('Labels:', iris['target_names'])
print('\nFeatures:', iris['feature_names'])
print('\nDescription:', iris['DESCR'])

Labels: ['setosa' 'versicolor' 'virginica']

Features: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Description: Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal wid

In [12]:
X = iris['data']
y = iris['target']
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [13]:
for i, x in enumerate(X[:10]) : print(x, y[i])

[5.1 3.5 1.4 0.2] 0
[4.9 3.  1.4 0.2] 0
[4.7 3.2 1.3 0.2] 0
[4.6 3.1 1.5 0.2] 0
[5.  3.6 1.4 0.2] 0
[5.4 3.9 1.7 0.4] 0
[4.6 3.4 1.4 0.3] 0
[5.  3.4 1.5 0.2] 0
[4.4 2.9 1.4 0.2] 0
[4.9 3.1 1.5 0.1] 0


In [16]:
import numpy as np

print(np.bincount(y))#istogramma di occorrenza di valori interi in un array

[50 50 50]


Dividiamo i dati in training e test set. Per prima cosa, mischiamo (coerentemente) i dati in modo casuale col metodo *shuffle*.

In [17]:
from sklearn.utils import shuffle

X, y = shuffle(X, y)
for i, x in enumerate(X[:10]) : print(x, y[i])

[4.6 3.1 1.5 0.2] 0
[6.9 3.1 5.1 2.3] 2
[6.2 2.2 4.5 1.5] 1
[4.9 3.1 1.5 0.1] 0
[6.5 3.  5.2 2. ] 2
[6.7 2.5 5.8 1.8] 2
[7.1 3.  5.9 2.1] 2
[6.4 3.2 5.3 2.3] 2
[6.9 3.1 5.4 2.1] 2
[5.7 4.4 1.5 0.4] 0


Prendiamo quindi due terzi degli esempi per l'addestramento, e i restanti per il test.

In [19]:
n_train = int(X.shape[0]/3)
print(X.shape[0], n_train)

150 50


In [20]:
X_train = X[:n_train]#i primi n_train esempi (righe)
X_test = X[n_train:]#gli altri
print(X_train.shape[0] + X_test.shape[0] == X.shape[0])

True


In [24]:
print(X_train.shape, X_test.shape)

(50, 4) (100, 4)


Analogamente per le etichette.

In [21]:
y_train, y_test = y[:n_train], y[n_train:]
print(y_train.shape[0] + y_test.shape[0] == y.shape[0])

True


Tramite il metodo *fit* addestriamo il modello sui dati di apprendimento. Il metodo opera in-place e retituisce il modello addestrato.

In [28]:
print(model.fit(X_train, y_train))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')


Una volta addestrato il modello, lo usiamo per predire la classe degli esempi del test set.

In [29]:
predictions = model.predict(X_test)
print(predictions.shape)
print(X_test.shape)

(100,)
(100, 4)


In [30]:
neighbors.KNeighborsClassifier().predict(X_test)

NotFittedError: Must fit neighbors before querying.

Infine, valutiamo le prestazioni (per esempio, l'accuratezza) del modello addestrato sull'insieme di test.

In [31]:
from sklearn.metrics import accuracy_score

print('Model accuracy on test set:', accuracy_score(y_test, predictions))

Model accuracy on test set: 0.91


Gli ultimi due passaggi possono essere fatti in un colpo solo col metodo *score*, esposto dal modello (addestrato).

In [32]:
print('Model accuracy on test set:', model.score(X_test, y_test))

Model accuracy on test set: 0.91


In [66]:
#sklearn scaling
#model selection
#alberi di decisione
#svm

<script>
  $(document).ready(function(){
    $('div.back-to-top').hide();
    $('nav#menubar').hide();
    $('div.prompt').hide();
    $('.hidden-print').hide();
  });
</script>

<footer id="attribution" style="float:right; color:#999; background:#fff;">
Created with Jupyter, delivered by Fastly, rendered by Rackspace.
</footer>