- [3.4](#3.4)
- [3.5](#3.5)
- [3.6](#3.6)
- [4.1, 4.2](#4.1,-4.2)
- [5.1](#5.1)
- [5.2](#5.2)
- [5.3](#5.3)
- [6.2](#6.2)
- [6.3](#6.3)
- [6.4](#6.4)
- [6.5](#6.5)
- [6.6](#6.6)
- [6.7](#6.7)
- [7.3](#7.3)
- [7.4](#7.4)

3.4
---

In [3]:
numbers = [10, 2, 4, 8, 1.7]
squared_numbers = []

for i, x in enumerate(numbers):
    print('Il numero in posizione {} è {}'.format(i, x))
    squared_numbers += [x**2]
    
squared_numbers

Il numero in posizione 0 è 10
Il numero in posizione 1 è 2
Il numero in posizione 2 è 4
Il numero in posizione 3 è 8
Il numero in posizione 4 è 1.7


[100, 4, 16, 64, 2.8899999999999997]

3.5
---

In [4]:
names = ['francesco', 'elisa', 'alessandro', 'giovanni', 'maria teresa']
indexed_sorted_names = [[i, n] for i, n in enumerate(sorted(names))]

indexed_sorted_names

[[0, 'alessandro'],
 [1, 'elisa'],
 [2, 'francesco'],
 [3, 'giovanni'],
 [4, 'maria teresa']]

3.6
---

In [5]:
numbers = [10, 2, 4, 8, 1.7]
squared_numbers = [x**2 for x in numbers]

squared_numbers

[100, 4, 16, 64, 2.8899999999999997]

4.1, 4.2
---

In [6]:
lst = [3,6,5,8,12]

for element in lst:
    if element**2 % 2 == 0 and element**2 % 3 == 0:
        print('Il quadrato di {} è {}, che è multiplo sia di 2 che di 3'.format(element, element**2))
    elif element**2 % 2 == 0:
        print('Il quadrato di {} è {}, che è multiplo di 2 ma non di 3'.format(element, element**2))
    elif element**2 % 3 == 0:
        print('Il quadrato di {} è {}, che è multiplo di 3 ma non di 2'.format(element, element**2))
    else:
        print('Il quadrato di {} è {}, che non è multiplo né di 2 né di 3'.format(element, element**2))
        
print('\n**************************************************************\n')

multiples_of_2 = [element**2 for element in lst if element**2 % 2 == 0]
multiples_of_3 = [element**2 for element in lst if element**2 % 3 == 0]
multiples_of_2_and_not_of_3 = [element**2 for element in lst if element**2 % 2 == 0 and not element**2 % 3 == 0]

print(multiples_of_2)
print(multiples_of_3)
print(multiples_of_2_and_not_of_3)

Il quadrato di 3 è 9, che è multiplo di 3 ma non di 2
Il quadrato di 6 è 36, che è multiplo sia di 2 che di 3
Il quadrato di 5 è 25, che non è multiplo né di 2 né di 3
Il quadrato di 8 è 64, che è multiplo di 2 ma non di 3
Il quadrato di 12 è 144, che è multiplo sia di 2 che di 3

**************************************************************

[36, 64, 144]
[9, 36, 144]
[64]


5.1
---

In [7]:
heights = {}
heights['Mount Everest'] = 8858
heights['K2'] = 8611
heights['Kangchenjunga'] = 8586

for mountain, height in heights.items():
    print('{} è alta {}'.format(mountain, height))
    
for i, mountain in enumerate(sorted(heights.keys())):
    print('La montagna numero {} è {} ed è alta {}'.format(i+1, mountain, heights[mountain]))

Mount Everest è alta 8858
K2 è alta 8611
Kangchenjunga è alta 8586
La montagna numero 1 è K2 ed è alta 8611
La montagna numero 2 è Kangchenjunga ed è alta 8586
La montagna numero 3 è Mount Everest ed è alta 8858


5.2
---

In [8]:
mountains = []

mountains += [{'name':'Mount Everest', 'height':8858, 'country':'Nepal'}]
mountains += [{'name':'K2', 'height':8611, 'country':'Pakistan'}]
mountains += [{'name':'Kangchenjunga', 'height':8586, 'country':'Nepal'}]

for i, m in enumerate(mountains):
    print('La montagna numero {} è {}, è alta {} e si trova in {}'.format(i,
                                                                          m['name'],
                                                                          m['height'],
                                                                          m['country']))

La montagna numero 0 è Mount Everest, è alta 8858 e si trova in Nepal
La montagna numero 1 è K2, è alta 8611 e si trova in Pakistan
La montagna numero 2 è Kangchenjunga, è alta 8586 e si trova in Nepal


In [9]:
mountain_names = [m['name'] for m in mountains]
mountain_heights = [m['height'] for m in mountains]

heights = {}

for i,n in enumerate(mountain_names):
    heights[n] = mountain_heights[i]
    
print(heights)

{'Mount Everest': 8858, 'K2': 8611, 'Kangchenjunga': 8586}


5.3
---

In [10]:
def show_estate_info(e):
    print('Paese: {}'.format(e['country']))
    print('Estensione (mq): {}'.format(e['extension']))
    print('Terreno annesso?: {}'.format('Sì' if e['has_land'] else 'No'))
    print('Prezzo: {}K Euro'.format(e['price']))

In [11]:
estates = []

e1 = {'country':'Italia',    'extension':2000,  'has_land':False, 'price':10}
e2 = {'country':'Spagna',    'extension':12000, 'has_land':False, 'price':125}
e3 = {'country':'Argentina', 'extension':50000, 'has_land':True,  'price':300}

estates += [e1, e2, e3]

for i, e in enumerate(estates):
    print(f'\nImmobile #{i}')#sintassi alternativa a format, disponibile da Python 3.6
    show_estate_info(e)


Immobile #0
Paese: Italia
Estensione (mq): 2000
Terreno annesso?: No
Prezzo: 10K Euro

Immobile #1
Paese: Spagna
Estensione (mq): 12000
Terreno annesso?: No
Prezzo: 125K Euro

Immobile #2
Paese: Argentina
Estensione (mq): 50000
Terreno annesso?: Sì
Prezzo: 300K Euro


6.2
---

In [12]:
import numpy as np
import numpy.random as rdm
from math import sqrt

def py_std(x):
    mean_val = sum(x) / len(x)
    return sqrt(sum((val-mean_val)**2 for val in x) / len(x))

large_array = rdm.normal(size=(1000000,))

print(py_std(large_array))
print(np.std(large_array))

#confronto tempi di esecuzione
%timeit py_std(large_array)
%timeit np.std(large_array)

0.9983962196795021
0.9983962196795204
843 ms ± 187 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
3.12 ms ± 214 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


6.3
---

In [13]:
import numpy as np
import numpy.random as rdm

n_frames = 50
n_pixel_y = 5
n_pixel_x = 5
movie = rdm.randint(0, 256, (n_frames, n_pixel_y, n_pixel_x))
print(movie)

[[[ 10 121 192  62  10]
  [100   8 117 122 213]
  [239 229 225 145 151]
  [233 221 204 163 169]
  [193 170  83  59 152]]

 [[ 14  51 182 198 135]
  [240  50 127 140  27]
  [124  77 111 134  10]
  [221 127  63 236 124]
  [  6 216   8 171 240]]

 [[  7  92 123  51  62]
  [ 77 165  80   6 181]
  [ 73 206 185  43 177]
  [  5 204 158  36  64]
  [169 234  98 160   0]]

 ...

 [[244  82 232 100  15]
  [ 46  36 225  49  92]
  [153  39 234 130 212]
  [133  31 145 161  50]
  [109 168  85 148 233]]

 [[ 27  43 200  18  63]
  [ 29 227 178 201  62]
  [174 241  19 234  53]
  [183 212  40  90 251]
  [ 90 138 156  60  81]]

 [[252 114 211 111  59]
  [179  49 154 104 100]
  [195 143 145   1  64]
  [115   8  97 114 248]
  [ 81  71 164 221  11]]]


In [14]:
print(movie.shape)

(50, 5, 5)


In [15]:
pixel_mean_intensity = np.mean(movie, axis=0)
print(pixel_mean_intensity)
print(pixel_mean_intensity.shape)

[[121.72 139.18 143.84 114.44 129.6 ]
 [138.24 124.66 134.   127.56 135.28]
 [136.88 151.9  113.38 130.12 110.18]
 [130.06 123.6  124.66 132.06 146.94]
 [145.   119.98 128.42 123.78 136.1 ]]
(5, 5)


6.4
---

In [16]:
import numpy as np
import numpy.random as rdm

values = rdm.normal(5, 3, 1000000)

#sottraggo 5 e guardo se ha funzionato
print(round(np.mean(values), 4))
values -= 5
print(round(np.mean(values), 4))

#implemento deviazione std e confronto con np.std
residuals = values - np.mean(values)
squared_residuals = residuals**2
variance = np.sum(squared_residuals) / values.size
print(np.std(values), np.sqrt(variance))

5.0003
0.0003
3.0009090647790866 3.0009090647790866


6.5
---

In [17]:
import numpy as np

X_train = np.array([[1,2,3],
                    [0,2,-1],
                    [-1,2,3],
                    [3,1,3]])

x_new = np.array([1,1,2])

y_train = np.array([0,1,0,1])

print(X_train)
print(y_train)
print(x_new)

[[ 1  2  3]
 [ 0  2 -1]
 [-1  2  3]
 [ 3  1  3]]
[0 1 0 1]
[1 1 2]


In [18]:
distances = [np.sqrt(np.sum((x - x_new) ** 2)) for x in X_train]#riga per riga
distances = np.round(distances, 1)
print(distances)

[1.4 3.3 2.4 2.2]


Posso calcolare le distanze in modo ancora più compatto. Definita la *Norma* di un vettore $d$-dimensionale,

$$\|x\|_2 := \sqrt{\sum_{i=1}^d x_i^2},$$

si può dire che la distanza euclidea tra due vettori $x$ e $x'$ è la norma del *vettore differenza* $x - x'$:

$$D(x, x') = \sqrt{\sum_{i=1}^{d}(x_i-x'_i)^2} = \|x - x'\|_2.$$

Proviamo intanto ad operare vettorialmente.

In [19]:
X_train - x_new#vettori differenza

array([[ 0,  1,  1],
       [-1,  1, -3],
       [-2,  1,  1],
       [ 2,  0,  1]])

In [20]:
(X_train - x_new) ** 2#differenze al quadrato

array([[0, 1, 1],
       [1, 1, 9],
       [4, 1, 1],
       [4, 0, 1]])

In [21]:
np.sum((X_train - x_new) ** 2, axis=1)#somma (lungo le colonne) degli scarti al quadrato

array([ 2, 11,  6,  5])

In [22]:
distances = np.sqrt(np.sum((X_train - x_new) ** 2, axis=1))#tutto vettoriale
distances = np.round(distances, 1)
print(distances)

[1.4 3.3 2.4 2.2]


Volendo, tutto in una riga:

In [23]:
print(np.round(np.sqrt(np.sum((X_train - x_new) ** 2, axis=1)), 1))

[1.4 3.3 2.4 2.2]


Adesso utilizziamo la funzione *norm* di numpy.

In [24]:
from numpy.linalg import norm

vec = np.random.random((5,))
print(vec)
print(np.sqrt(np.sum(vec**2)))
print(norm(vec))

[0.37302077 0.08657242 0.13471425 0.60975698 0.6514999 ]
0.9803279509839358
0.9803279509839358


In [25]:
print(np.round(norm(X_train - x_new, axis=1), 1))#utilizzando la norma vettorialmente

[1.4 3.3 2.4 2.2]


**Nota**: abbiamo smesso di scrivere cicli for!

6.6
---

In [26]:
people = np.array([[1.60, 66],
                   [1.60, 63],
                   [1.90, 67]])

print(people)

[[ 1.6 66. ]
 [ 1.6 63. ]
 [ 1.9 67. ]]


In [27]:
A, B, C = people
print(A)
print(B)
print(C)

[ 1.6 66. ]
[ 1.6 63. ]
[ 1.9 67. ]


In [28]:
print(norm(A-B))
print(norm(A-C))

3.0
1.0440306508910548


In [29]:
def scale_01(column):
    return (column - np.min(column)) / (np.max(column) - np.min(column))

scaled_height = scale_01(people[:, 0])
scaled_weight = scale_01(people[:, 1])

print(scaled_height)
print(scaled_weight)

[0. 0. 1.]
[0.75 0.   1.  ]


In [30]:
scaled_people = np.vstack([scaled_height, scaled_weight])
print(scaled_people)

[[0.   0.   1.  ]
 [0.75 0.   1.  ]]


In [31]:
scaled_people = scaled_people.T#trasposizione
print(scaled_people)

[[0.   0.75]
 [0.   0.  ]
 [1.   1.  ]]


Scriviamo tutto in modo più veloce e compatto, utilizzando il calcolo vettoriale.

In [32]:
print(people)

[[ 1.6 66. ]
 [ 1.6 63. ]
 [ 1.9 67. ]]


In [33]:
print(np.min(people, axis=0))#minimo per colonna (cioè, 'lungo le righe')

[ 1.6 63. ]


In [34]:
print(people - np.min(people, axis=0))

[[0.  3. ]
 [0.  0. ]
 [0.3 4. ]]


In [35]:
print(np.max(people, axis=0) - np.min(people, axis=0))

[0.3 4. ]


In [36]:
scaled_people = (people - np.min(people, axis=0)) / (np.max(people, axis=0) - np.min(people, axis=0))
print(scaled_people)

[[0.   0.75]
 [0.   0.  ]
 [1.   1.  ]]


In [37]:
scaled_A, scaled_B, scaled_C = scaled_people
print(scaled_A)
print(scaled_B)
print(scaled_C)

[0.   0.75]
[0. 0.]
[1. 1.]


In [38]:
print(norm(scaled_A-scaled_B))
print(norm(scaled_A-scaled_C))

0.75
1.0307764064044151


6.7
---

In [39]:
import numpy as np
from numpy.linalg import norm

np.random.seed(0)#fisso il generatore casuale per la riproducibilità dell'esperimento

def KNN(k, X, y, x):
    distances = norm(X - x, axis=1)
    sorted_labels = y[distances.argsort()]
    return np.argmax(np.bincount(sorted_labels[:k]))

def one_line_KNN(k, X, y, x):
    return np.argmax(np.bincount(y[norm(X - x, axis=1).argsort()][:k]))

X_train = np.random.random((7,4))
y_train = np.random.randint(0, 2, (7))
x_new = np.random.random((4,))

print('Matrice delle feature:\n', X_train)

print('\nVettore delle etichette:', y_train)

print('\nNuovo esempio da classificare:', x_new)

print('\nPredizione (k=3):', one_line_KNN(3, X_train, y_train, x_new))
print('Predizione (k=5):', one_line_KNN(5, X_train, y_train, x_new))

Matrice delle feature:
 [[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]
 [0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918]
 [0.11827443 0.63992102 0.14335329 0.94466892]]

Vettore delle etichette: [1 0 0 1 1 0 1]

Nuovo esempio da classificare: [0.73691818 0.21655035 0.13521817 0.32414101]

Predizione (k=3): 1
Predizione (k=5): 0


7.3
---

In [40]:
#Importo librerie
from sklearn import datasets, neighbors
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsRegressor as KNN
from sklearn.metrics import mean_absolute_error

#Carico il dataset
boston = datasets.load_boston()
X, y = boston['data'], boston['target']

print(boston['DESCR'])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [41]:
#Scalo le feature tra 0 e 1
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

#Separo train e test
X, y = shuffle(X, y, random_state=0)
X_train, X_test = X[:400], X[400:]
y_train, y_test = y[:400], y[400:]

#Addestro il modello
model = KNN(n_neighbors=3).fit(X_train, y_train)

#Ottengo predizioni e valuto il mae
predictions = model.predict(X_test)
mae = mean_absolute_error(y_test, predictions)
print('Model MAE on test set: {:.3f}'.format(mae))

Model MAE on test set: 2.845


7.4
---

In [42]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import MinMaxScaler
from sklearn.utils import shuffle
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.metrics import accuracy_score
import numpy as np

#Carico il dataset
iris = load_iris()
X, y = iris['data'], iris['target']

#Scalo le feature tra 0 e 1
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

#Separo train , validation e test
X, y = shuffle(X, y, random_state=123)
X_tr, X_val, X_test = X[:75], X[75:100], X[100:]
y_tr, y_val, y_test = y[:75], y[75:100], y[100:]

print(X_tr.shape, X_val.shape, X_test.shape)

(75, 4) (25, 4) (50, 4)


In [43]:
for k in [1,2,3,5,10]:
    model = KNN(n_neighbors=k)
    model.fit(X_tr, y_tr)
    predictions = model.predict(X_val)
    validation_accuracy = accuracy_score(y_val, predictions)
    print('Validation accuracy with k {}: {:.2f}'.format(k, validation_accuracy))   

Validation accuracy with k 1: 0.92
Validation accuracy with k 2: 0.96
Validation accuracy with k 3: 0.92
Validation accuracy with k 5: 0.92
Validation accuracy with k 10: 0.92


In [44]:
X_train = np.vstack([X_tr, X_val])
y_train = np.hstack([y_tr, y_val])

print(X_train.shape, y_train.shape)

(100, 4) (100,)


In [45]:
predictions = KNN(n_neighbors=2).fit(X_train, y_train).predict(X_test)
print('Test accuracy:', accuracy_score(y_test, predictions))

Test accuracy: 0.96


In questo caso utilizzare tutti i dati del training set per il test finale non ha migliorato l'accuratezza del modello.

<script>
  $(document).ready(function(){
    $('div.back-to-top').hide();
    $('nav#menubar').hide();
    $('div.prompt').hide();
    $('.hidden-print').hide();
  });
</script>

<footer id="attribution" style="float:right; color:#999; background:#fff;">
Created with Jupyter, delivered by Fastly, rendered by Rackspace.
</footer>