- [3.1](#3.1)
- [3.2](#3.2)
- [4.1, 4.2](#4.1,-4.2)
- [5.1, 5.2, 5.3](#5.1,-5.2,-5.3)
- [5.4, 5.5](#5.4,-5.5)
- [6.2](#6.2)
- [6.3](#6.3)
- [6.4](#6.4)
- [KNN1](#KNN1)
- [KNN2](#KNN2)

3.1
---

In [84]:
heights = {}
heights['Mount Everest'] = 8858
heights['K2'] = 8611
heights['Kangchenjunga'] = 8586

for mountain, height in heights.items():
    print('{} è alta {}'.format(mountain, height))
    
for i, mountain in enumerate(sorted(heights.keys())):
    print('La montagna numero {} è {} ed è alta {}'.format(i+1, mountain, heights[mountain]))

Mount Everest è alta 8858
K2 è alta 8611
Kangchenjunga è alta 8586
La montagna numero 1 è K2 ed è alta 8611
La montagna numero 2 è Kangchenjunga ed è alta 8586
La montagna numero 3 è Mount Everest ed è alta 8858


3.2
---

In [85]:
mountains = []

mountains += [{'name':'Mount Everest', 'height':8858, 'country':'Nepal'}]
mountains += [{'name':'K2', 'height':8611, 'country':'Pakistan'}]
mountains += [{'name':'Kangchenjunga', 'height':8586, 'country':'Nepal'}]

for i, m in enumerate(mountains):
    print('La montagna numero {} è {}, è alta {} e si trova in {}'.format(i,
                                                                          m['name'],
                                                                          m['height'],
                                                                          m['country']))

La montagna numero 0 è Mount Everest, è alta 8858 e si trova in Nepal
La montagna numero 1 è K2, è alta 8611 e si trova in Pakistan
La montagna numero 2 è Kangchenjunga, è alta 8586 e si trova in Nepal


In [86]:
mountain_names = [m['name'] for m in mountains]
mountain_heights = [m['height'] for m in mountains]

heights = {}

for i,n in enumerate(mountain_names):
    heights[n] = mountain_heights[i]
    
print(heights)

{'Mount Everest': 8858, 'K2': 8611, 'Kangchenjunga': 8586}


4.1, 4.2
---

In [87]:
lst = [3,6,5,8,12]

for element in lst:
    if element**2 % 2 == 0 and element**2 % 3 == 0:
        print('Il quadrato di %d è %d, che è multiplo sia di 2 che di 3' % (element, element**2))
    elif element**2 % 2 == 0:
        print('Il quadrato di %d è %d, che è multiplo di 2 ma non di 3' % (element, element**2))
    elif element**2 % 3 == 0:
        print('Il quadrato di %d è %d, che è multiplo di 3 ma non di 2' % (element, element**2))
    else:
        print('Il quadrato di %d è %d, che non è multiplo né di 2 né di 3' %  (element, element**2))
        
print('\n*******************\n')

multiples_of_2 = [element**2 for element in lst if element**2 % 2 == 0]
multiples_of_3 = [element**2 for element in lst if element**2 % 3 == 0]
multiples_of_2_and_not_of_3 = [element**2 for element in lst if element**2 % 2 == 0 and not element**2 % 3 == 0]

print(multiples_of_2)
print(multiples_of_3)
print(multiples_of_2_and_not_of_3)

Il quadrato di 3 è 9, che è multiplo di 3 ma non di 2
Il quadrato di 6 è 36, che è multiplo sia di 2 che di 3
Il quadrato di 5 è 25, che non è multiplo né di 2 né di 3
Il quadrato di 8 è 64, che è multiplo di 2 ma non di 3
Il quadrato di 12 è 144, che è multiplo sia di 2 che di 3

*******************

[36, 64, 144]
[9, 36, 144]
[64]


5.1, 5.2, 5.3
---

In [88]:
def show_user_info(user):
    print('\nNome:', user['name'])
    print('Età:', user['age'])
    print('Sesso:', user['sex'])

def show_all_users_by_age(users):
    for s in sorted(users, key = lambda x : x['age']):
        show_user_info(s)
        
def show_all_users_by_field(users, field='name'):
    for s in sorted(users, key = lambda x : x[field]):
        show_user_info(s)
        
def show_names_alphabetically(users):
    for name in sorted([u['name'] for u in users]):
        print(name)
    
francesco = {'name':'Francesco', 'age':30, 'sex':'M'}
giovanni = {'name':'Giovanni', 'age':68, 'sex':'M'}
elisa = {'name':'Elisa', 'age':27, 'sex':'F'}
michael = {'name':'Michael', 'age':30, 'sex':'M'}

users = [francesco, giovanni, elisa, michael]

print('Lista utenti per età:')
show_all_users_by_age(users)
print('\n*****************************')

print('\nLista utenti per età:')
show_all_users_by_field(users, field='age')
print('\n*****************************')

print('\nLista utenti per nome:')
show_all_users_by_field(users)
print('\n*****************************')

print('\nLista dei nomi degli utenti in ordine alfabetico:\n')
show_names_alphabetically(users)

Lista utenti per età:

Nome: Elisa
Età: 27
Sesso: F

Nome: Francesco
Età: 30
Sesso: M

Nome: Michael
Età: 30
Sesso: M

Nome: Giovanni
Età: 68
Sesso: M

*****************************

Lista utenti per età:

Nome: Elisa
Età: 27
Sesso: F

Nome: Francesco
Età: 30
Sesso: M

Nome: Michael
Età: 30
Sesso: M

Nome: Giovanni
Età: 68
Sesso: M

*****************************

Lista utenti per nome:

Nome: Elisa
Età: 27
Sesso: F

Nome: Francesco
Età: 30
Sesso: M

Nome: Giovanni
Età: 68
Sesso: M

Nome: Michael
Età: 30
Sesso: M

*****************************

Lista dei nomi degli utenti in ordine alfabetico:

Elisa
Francesco
Giovanni
Michael


5.4, 5.5
---

In [89]:
def is_adult(user):
    return user['age'] >= 18

def show_and_add_if_adult(user, db):
    show_user_info(user)
    #5.4
    #return db + [user] if user['age'] >= 18 else db
    #5.5
    return db + [user] if is_adult(user) else db

adult_users = []#database

print('\nTutti gli utenti:')
adult_users = show_and_add_if_adult({'name':'Francesco', 'age':30, 'sex':'M'}, adult_users)
adult_users = show_and_add_if_adult({'name':'Giovanni', 'age':68, 'sex':'M'}, adult_users)
adult_users = show_and_add_if_adult({'name':'Giulia', 'age':16, 'sex':'F'}, adult_users)
print('\n*****************************')

print('\nUtenti maggiorenni:')
for a in adult_users : show_user_info(a)


Tutti gli utenti:

Nome: Francesco
Età: 30
Sesso: M

Nome: Giovanni
Età: 68
Sesso: M

Nome: Giulia
Età: 16
Sesso: F

*****************************

Utenti maggiorenni:

Nome: Francesco
Età: 30
Sesso: M

Nome: Giovanni
Età: 68
Sesso: M


6.2
---

In [90]:
import numpy as np
import numpy.random as rdm
from math import sqrt

def py_std(X):
    X_mean = sum(X) / len(X)
    return sqrt(sum((x-X_mean)**2 for x in X) / len(X))

large_array = rdm.normal(size=(1000000,))

print(py_std(large_array))
print(np.std(large_array))
%timeit py_std(large_array)
%timeit np.std(large_array)

0.999134485262745
0.9991344852627513
342 ms ± 17.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.79 ms ± 213 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


6.3
---

In [91]:
import numpy as np
import numpy.random as rdm

n_frames = 50
n_pixel_x = 5
n_pixel_y = 5
movie = rdm.randint(256, size=(n_frames, n_pixel_x, n_pixel_y))
print(movie)

[[[199 105 118 252  23]
  [ 32 190  83 184 122]
  [ 57  13   5  10 225]
  [250 197  93 184  59]
  [117  25  79 180  51]]

 [[166 218  12  71 253]
  [ 96 213 162  37 246]
  [109 119 179 185 218]
  [ 82  81  33 113 108]
  [  6 232 149  92 195]]

 [[245 189  26  47  91]
  [191  45  38 157 125]
  [188  14  89 185 189]
  [112  60 206 177  14]
  [118 135   9 231  60]]

 ...

 [[ 33 200 170 220 252]
  [132 159 215 100  26]
  [223  95  49 225 169]
  [115 239 139  32  45]
  [177  33  96  40 235]]

 [[143 109  15  37  16]
  [111  54  82  78  43]
  [ 95 133 156 128 107]
  [212  79 141  53 137]
  [ 97 102 107 231  45]]

 [[188 153 254 223 233]
  [239 220  14 206  58]
  [182 178  88  74  78]
  [ 94  60  57  99 230]
  [103 111 180 163 213]]]


In [92]:
print(movie.shape)

(50, 5, 5)


In [93]:
pixel_mean_intensity = np.mean(movie, axis=0)
print(pixel_mean_intensity)
print(pixel_mean_intensity.shape)

[[135.54 115.88 128.8  120.28 125.7 ]
 [143.14 133.44 117.78 127.32 129.2 ]
 [125.18 129.34 110.64 129.16 136.16]
 [138.04 126.92 131.84 140.36 131.34]
 [119.04 123.2  127.08 138.56 143.46]]
(5, 5)


6.4
---

In [94]:
import numpy as np
import numpy.random as rdm

values = rdm.normal(5, 3, 1000000)

values -= 5
residuals = values - np.mean(values)
squared_residuals = residuals**2
variance = np.sum(squared_residuals) / values.size
print(np.std(values), np.sqrt(variance))

3.002138317145509 3.002138317145509


6.5
---

In [95]:
import numpy as np
from numpy.linalg import norm

np.random.seed(0)

def KNN(k, X, y, x):
    distances = norm(X_train - x_new, axis=1)
    sorted_labels = y_train[distances.argsort()]
    return np.argmax(np.bincount(sorted_labels[:k]))

def one_line_KNN(k, X, y, x):
    return np.argmax(np.bincount(y_train[norm(X_train - x_new, axis=1).argsort()][:k]))

X_train = np.random.random((7,4))
y_train = np.random.randint(0, 2, (7))
x_new = np.random.random(4)

print('Matrice delle feature:', X_train)

print('\nVettore delle etichette:', y_train)

print('\nNuovo esempio da classificare:', x_new)

print('\nPredizione (k=3):', one_line_KNN(3, X_train, y_train, x_new))
print('Predizione (k=5):', one_line_KNN(5, X_train, y_train, x_new))

Matrice delle feature: [[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]
 [0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918]
 [0.11827443 0.63992102 0.14335329 0.94466892]]

Vettore delle etichette: [1 0 0 1 1 0 1]

Nuovo esempio da classificare: [0.73691818 0.21655035 0.13521817 0.32414101]

Predizione (k=3): 1
Predizione (k=5): 0


KNN1
---

In [96]:
import numpy as np

X_train = np.array([[1,2,3],
                    [0,2,-1],
                    [-1,2,3],
                    [3,1,3]])

x_new = np.array([1,1,2])

y_train = np.array([0,1,0,1])

print(X_train)
print(y_train)
print(x_new)

[[ 1  2  3]
 [ 0  2 -1]
 [-1  2  3]
 [ 3  1  3]]
[0 1 0 1]
[1 1 2]


In [97]:
distances = [np.sqrt(np.sum((x - x_new) ** 2)) for x in X_train]#riga per riga
distances = np.round(distances, 2)
print(distances)

[1.41 3.32 2.45 2.24]


Posso calcolare le distanze in modo ancora più compatto:

In [98]:
(X_train - x_new) ** 2#differenze al quadrato

array([[0, 1, 1],
       [1, 1, 9],
       [4, 1, 1],
       [4, 0, 1]])

In [99]:
np.sum((X_train - x_new) ** 2, axis=1)#somma (lungo le colonne) degli scarti al quadrato

array([ 2, 11,  6,  5])

In [100]:
distances = np.sqrt(np.sum((X_train - x_new) ** 2, axis=1))#tutto vettoriale
distances = np.round(distances, 2)
print(distances)

[1.41 3.32 2.45 2.24]


Quindi, tutto in una riga:

In [101]:
print(np.round(np.sqrt(np.sum((X_train - x_new) ** 2, axis=1)), 2))

[1.41 3.32 2.45 2.24]


*Norma* di un vettore $d$-dimensionale: $\|x\|_2 := \sqrt{\frac{1}{d}\displaystyle\sum_1^d x_i^2}$.

In [102]:
from numpy.linalg import norm

vec = np.random.random((5,))
print(vec)
print(np.sqrt(np.sum(vec**2)))
print(norm(vec))

[0.14967487 0.22232139 0.38648898 0.90259848 0.44994999]
1.1128082042838254
1.1128082042838254


La distanza euclidea tra due vettori $x$ e $x'$ è la norma del vettore differenza $x - x'$.

In [103]:
print(X_train - x_new)#matrice dei vettori differenza

[[ 0  1  1]
 [-1  1 -3]
 [-2  1  1]
 [ 2  0  1]]


In [104]:
print(np.round(norm(X_train - x_new, axis=1), 2))#norma delle differenze (lungo le colonne!)

[1.41 3.32 2.45 2.24]


**Nota**: abbiamo smesso di scrivere cicli for!

KNN2
---

In [105]:
people = np.array([[1.60, 66],
                   [1.60, 63],
                   [1.90, 67]])

print(people)

[[ 1.6 66. ]
 [ 1.6 63. ]
 [ 1.9 67. ]]


In [106]:
A, B, C = people
print(A)
print(B)
print(C)

[ 1.6 66. ]
[ 1.6 63. ]
[ 1.9 67. ]


In [107]:
print(norm(A-B))
print(norm(A-C))

3.0
1.0440306508910548


In [108]:
def scale_01(column):
    return (column - np.min(column)) / (np.max(column) - np.min(column))

scaled_height = scale_01(people[:, 0])
scaled_weight = scale_01(people[:, 1])

print(scaled_height)
print(scaled_weight)

[0. 0. 1.]
[0.75 0.   1.  ]


In [109]:
scaled_people = np.vstack([scaled_height, scaled_weight])
print(scaled_people)

[[0.   0.   1.  ]
 [0.75 0.   1.  ]]


In [110]:
scaled_people = scaled_people.T#trasposizione
print(scaled_people)

[[0.   0.75]
 [0.   0.  ]
 [1.   1.  ]]


In [111]:
#implementazione più compatta
scaled_people = (people - np.min(people, axis=0)) / (np.max(people, axis=0) - np.min(people, axis=0))
print(scaled_people)

[[0.   0.75]
 [0.   0.  ]
 [1.   1.  ]]


In [112]:
scaled_A, scaled_B, scaled_C = scaled_people
print(scaled_A)
print(scaled_B)
print(scaled_C)

[0.   0.75]
[0. 0.]
[1. 1.]


In [113]:
print(norm(scaled_A-scaled_B))
print(norm(scaled_A-scaled_C))

0.75
1.0307764064044151


<script>
  $(document).ready(function(){
    $('div.back-to-top').hide();
    $('nav#menubar').hide();
    $('div.prompt').hide();
    $('.hidden-print').hide();
  });
</script>

<footer id="attribution" style="float:right; color:#999; background:#fff;">
Created with Jupyter, delivered by Fastly, rendered by Rackspace.
</footer>