- [3.1](#3.1)
- [3.2](#3.2)
- [4.1, 4.2](#4.1,-4.2)
- [5.1, 5.2, 5.3](#5.1,-5.2,-5.3)
- [5.4, 5.5](#5.4,-5.5)
- [6.2](#6.2)
- [6.3](#6.3)
- [6.4](#6.4)
- [6.5](#6.5)
- [KNN1](#KNN1)
- [KNN2](#KNN2)
- [7.4](#7.4)

In [84]:
heights = {}
heights['Mount Everest'] = 8858
heights['K2'] = 8611
heights['Kangchenjunga'] = 8586

for mountain, height in heights.items():
    print('{} è alta {}'.format(mountain, height))
    
for i, mountain in enumerate(sorted(heights.keys())):
    print('La montagna numero {} è {} ed è alta {}'.format(i+1, mountain, heights[mountain]))

Mount Everest è alta 8858
K2 è alta 8611
Kangchenjunga è alta 8586
La montagna numero 1 è K2 ed è alta 8611
La montagna numero 2 è Kangchenjunga ed è alta 8586
La montagna numero 3 è Mount Everest ed è alta 8858


3.2
---

In [85]:
mountains = []

mountains += [{'name':'Mount Everest', 'height':8858, 'country':'Nepal'}]
mountains += [{'name':'K2', 'height':8611, 'country':'Pakistan'}]
mountains += [{'name':'Kangchenjunga', 'height':8586, 'country':'Nepal'}]

for i, m in enumerate(mountains):
    print('La montagna numero {} è {}, è alta {} e si trova in {}'.format(i,
                                                                          m['name'],
                                                                          m['height'],
                                                                          m['country']))

La montagna numero 0 è Mount Everest, è alta 8858 e si trova in Nepal
La montagna numero 1 è K2, è alta 8611 e si trova in Pakistan
La montagna numero 2 è Kangchenjunga, è alta 8586 e si trova in Nepal


In [86]:
mountain_names = [m['name'] for m in mountains]
mountain_heights = [m['height'] for m in mountains]

heights = {}

for i,n in enumerate(mountain_names):
    heights[n] = mountain_heights[i]
    
print(heights)

{'Mount Everest': 8858, 'K2': 8611, 'Kangchenjunga': 8586}


4.1, 4.2
---

In [87]:
lst = [3,6,5,8,12]

for element in lst:
    if element**2 % 2 == 0 and element**2 % 3 == 0:
        print('Il quadrato di %d è %d, che è multiplo sia di 2 che di 3' % (element, element**2))
    elif element**2 % 2 == 0:
        print('Il quadrato di %d è %d, che è multiplo di 2 ma non di 3' % (element, element**2))
    elif element**2 % 3 == 0:
        print('Il quadrato di %d è %d, che è multiplo di 3 ma non di 2' % (element, element**2))
    else:
        print('Il quadrato di %d è %d, che non è multiplo né di 2 né di 3' %  (element, element**2))
        
print('\n*******************\n')

multiples_of_2 = [element**2 for element in lst if element**2 % 2 == 0]
multiples_of_3 = [element**2 for element in lst if element**2 % 3 == 0]
multiples_of_2_and_not_of_3 = [element**2 for element in lst if element**2 % 2 == 0 and not element**2 % 3 == 0]

print(multiples_of_2)
print(multiples_of_3)
print(multiples_of_2_and_not_of_3)

Il quadrato di 3 è 9, che è multiplo di 3 ma non di 2
Il quadrato di 6 è 36, che è multiplo sia di 2 che di 3
Il quadrato di 5 è 25, che non è multiplo né di 2 né di 3
Il quadrato di 8 è 64, che è multiplo di 2 ma non di 3
Il quadrato di 12 è 144, che è multiplo sia di 2 che di 3

*******************

[36, 64, 144]
[9, 36, 144]
[64]


5.1, 5.2, 5.3
---

In [88]:
def show_user_info(user):
    print('\nNome:', user['name'])
    print('Età:', user['age'])
    print('Sesso:', user['sex'])

def show_all_users_by_age(users):
    for s in sorted(users, key = lambda x : x['age']):
        show_user_info(s)
        
def show_all_users_by_field(users, field='name'):
    for s in sorted(users, key = lambda x : x[field]):
        show_user_info(s)
        
def show_names_alphabetically(users):
    for name in sorted([u['name'] for u in users]):
        print(name)
    
francesco = {'name':'Francesco', 'age':30, 'sex':'M'}
giovanni = {'name':'Giovanni', 'age':68, 'sex':'M'}
elisa = {'name':'Elisa', 'age':27, 'sex':'F'}
michael = {'name':'Michael', 'age':30, 'sex':'M'}

users = [francesco, giovanni, elisa, michael]

print('Lista utenti per età:')
show_all_users_by_age(users)
print('\n*****************************')

print('\nLista utenti per età:')
show_all_users_by_field(users, field='age')
print('\n*****************************')

print('\nLista utenti per nome:')
show_all_users_by_field(users)
print('\n*****************************')

print('\nLista dei nomi degli utenti in ordine alfabetico:\n')
show_names_alphabetically(users)

Lista utenti per età:

Nome: Elisa
Età: 27
Sesso: F

Nome: Francesco
Età: 30
Sesso: M

Nome: Michael
Età: 30
Sesso: M

Nome: Giovanni
Età: 68
Sesso: M

*****************************

Lista utenti per età:

Nome: Elisa
Età: 27
Sesso: F

Nome: Francesco
Età: 30
Sesso: M

Nome: Michael
Età: 30
Sesso: M

Nome: Giovanni
Età: 68
Sesso: M

*****************************

Lista utenti per nome:

Nome: Elisa
Età: 27
Sesso: F

Nome: Francesco
Età: 30
Sesso: M

Nome: Giovanni
Età: 68
Sesso: M

Nome: Michael
Età: 30
Sesso: M

*****************************

Lista dei nomi degli utenti in ordine alfabetico:

Elisa
Francesco
Giovanni
Michael


5.4, 5.5
---

In [89]:
def is_adult(user):
    return user['age'] >= 18

def show_and_add_if_adult(user, db):
    show_user_info(user)
    #5.4
    #return db + [user] if user['age'] >= 18 else db
    #5.5
    return db + [user] if is_adult(user) else db

adult_users = []#database

print('\nTutti gli utenti:')
adult_users = show_and_add_if_adult({'name':'Francesco', 'age':30, 'sex':'M'}, adult_users)
adult_users = show_and_add_if_adult({'name':'Giovanni', 'age':68, 'sex':'M'}, adult_users)
adult_users = show_and_add_if_adult({'name':'Giulia', 'age':16, 'sex':'F'}, adult_users)
print('\n*****************************')

print('\nUtenti maggiorenni:')
for a in adult_users : show_user_info(a)


Tutti gli utenti:

Nome: Francesco
Età: 30
Sesso: M

Nome: Giovanni
Età: 68
Sesso: M

Nome: Giulia
Età: 16
Sesso: F

*****************************

Utenti maggiorenni:

Nome: Francesco
Età: 30
Sesso: M

Nome: Giovanni
Età: 68
Sesso: M


6.2
---

In [2]:
import numpy as np
import numpy.random as rdm
from math import sqrt

def py_std(x):
    mean_val = sum(x) / len(x)
    return sqrt(sum((val-mean_val)**2 for val in x) / len(x))

large_array = rdm.normal(size=(1000000,))

print(py_std(large_array))
print(np.std(large_array))
%timeit py_std(large_array)
%timeit np.std(large_array)

0.9992693936220786
0.9992693936220851
323 ms ± 1.59 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.3 ms ± 15.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


6.3
---

In [1]:
import numpy as np
import numpy.random as rdm

n_frames = 50
n_pixel_x = 5
n_pixel_y = 5
movie = rdm.randint(0, 256, (n_frames, n_pixel_x, n_pixel_y))
print(movie)

[[[175  37 192 120 181]
  [ 15 114 217 168  95]
  [190 174 175 107 203]
  [250 210 189 229  47]
  [169 110 130 148 160]]

 [[ 72 194 176 105 244]
  [ 16 250 136 153  28]
  [110  61 159  98   5]
  [ 90 233 151 244 235]
  [136 123  25 225 141]]

 [[ 28 168 112 247 165]
  [ 58  69 212 204 153]
  [174  90 164  52  28]
  [ 92 226 183 255 100]
  [190 169 199 242 201]]

 ...

 [[148  81 144  29   5]
  [219 118 185  42 248]
  [248 136  94  25  55]
  [135  37  51  90   4]
  [ 66 188  50 109  93]]

 [[ 78 192 135  75 109]
  [ 85  27  48  51  25]
  [135 161 227  71 177]
  [229 240 251 114 152]
  [129  27 187 131 140]]

 [[157  25 163 205  31]
  [193 138  83 111 183]
  [ 43 245 163 253 139]
  [ 65  35  44 248 135]
  [ 98  24 148 225 123]]]


In [2]:
print(movie.shape)

(50, 5, 5)


In [3]:
pixel_mean_intensity = np.mean(movie, axis=0)
print(pixel_mean_intensity)
print(pixel_mean_intensity.shape)

[[114.48 110.74 142.62 114.56 123.72]
 [124.78 132.6  121.52 111.9  118.92]
 [129.82 121.78 113.22 129.1  147.8 ]
 [139.24 128.6  149.04 146.88 132.04]
 [124.98 124.86 129.32 143.84 112.62]]
(5, 5)


6.4
---

In [7]:
import numpy as np
import numpy.random as rdm

values = rdm.normal(5, 3, 1000000)

#levo 5 e guardo se ha funzionato
print(round(np.mean(values), 4))
values -= 5
print(5 + round(np.mean(values), 4))

#implemento deviazione std e confronto con np.std
residuals = values - np.mean(values)
squared_residuals = residuals**2
variance = np.sum(squared_residuals) / values.size
print(np.std(values), np.sqrt(variance))

5.0015
5.0015
2.996396470884666 2.996396470884666


6.5
---

In [1]:
import numpy as np
from numpy.linalg import norm

np.random.seed(0)#fisso il generatore casuale per la riproducibilità dell'esperimento

def KNN(k, X, y, x):
    distances = norm(X - x, axis=1)
    sorted_labels = y[distances.argsort()]
    return np.argmax(np.bincount(sorted_labels[:k]))

def one_line_KNN(k, X, y, x):
    return np.argmax(np.bincount(y[norm(X - x, axis=1).argsort()][:k]))

X_train = np.random.random((7,4))
y_train = np.random.randint(0, 2, (7))
x_new = np.random.random((4,))

print('Matrice delle feature:\n', X_train)

print('\nVettore delle etichette:', y_train)

print('\nNuovo esempio da classificare:', x_new)

print('\nPredizione (k=3):', one_line_KNN(3, X_train, y_train, x_new))
print('Predizione (k=5):', one_line_KNN(5, X_train, y_train, x_new))

Matrice delle feature:
 [[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]
 [0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918]
 [0.11827443 0.63992102 0.14335329 0.94466892]]

Vettore delle etichette: [1 0 0 1 1 0 1]

Nuovo esempio da classificare: [0.73691818 0.21655035 0.13521817 0.32414101]

Predizione (k=3): 1
Predizione (k=5): 0


KNN1
---

In [96]:
import numpy as np

X_train = np.array([[1,2,3],
                    [0,2,-1],
                    [-1,2,3],
                    [3,1,3]])

x_new = np.array([1,1,2])

y_train = np.array([0,1,0,1])

print(X_train)
print(y_train)
print(x_new)

[[ 1  2  3]
 [ 0  2 -1]
 [-1  2  3]
 [ 3  1  3]]
[0 1 0 1]
[1 1 2]


In [97]:
distances = [np.sqrt(np.sum((x - x_new) ** 2)) for x in X_train]#riga per riga
distances = np.round(distances, 2)
print(distances)

[1.41 3.32 2.45 2.24]


Posso calcolare le distanze in modo ancora più compatto:

In [98]:
(X_train - x_new) ** 2#differenze al quadrato

array([[0, 1, 1],
       [1, 1, 9],
       [4, 1, 1],
       [4, 0, 1]])

In [99]:
np.sum((X_train - x_new) ** 2, axis=1)#somma (lungo le colonne) degli scarti al quadrato

array([ 2, 11,  6,  5])

In [100]:
distances = np.sqrt(np.sum((X_train - x_new) ** 2, axis=1))#tutto vettoriale
distances = np.round(distances, 2)
print(distances)

[1.41 3.32 2.45 2.24]


Quindi, tutto in una riga:

In [101]:
print(np.round(np.sqrt(np.sum((X_train - x_new) ** 2, axis=1)), 2))

[1.41 3.32 2.45 2.24]


*Norma* di un vettore $d$-dimensionale: $\|x\|_2 := \sqrt{\frac{1}{d}\displaystyle\sum_1^d x_i^2}$.

In [102]:
from numpy.linalg import norm

vec = np.random.random((5,))
print(vec)
print(np.sqrt(np.sum(vec**2)))
print(norm(vec))

[0.14967487 0.22232139 0.38648898 0.90259848 0.44994999]
1.1128082042838254
1.1128082042838254


La distanza euclidea tra due vettori $x$ e $x'$ è la norma del vettore differenza $x - x'$.

In [103]:
print(X_train - x_new)#matrice dei vettori differenza

[[ 0  1  1]
 [-1  1 -3]
 [-2  1  1]
 [ 2  0  1]]


In [104]:
print(np.round(norm(X_train - x_new, axis=1), 2))#norma delle differenze (lungo le colonne!)

[1.41 3.32 2.45 2.24]


**Nota**: abbiamo smesso di scrivere cicli for!

KNN2
---

In [105]:
people = np.array([[1.60, 66],
                   [1.60, 63],
                   [1.90, 67]])

print(people)

[[ 1.6 66. ]
 [ 1.6 63. ]
 [ 1.9 67. ]]


In [106]:
A, B, C = people
print(A)
print(B)
print(C)

[ 1.6 66. ]
[ 1.6 63. ]
[ 1.9 67. ]


In [107]:
print(norm(A-B))
print(norm(A-C))

3.0
1.0440306508910548


In [108]:
def scale_01(column):
    return (column - np.min(column)) / (np.max(column) - np.min(column))

scaled_height = scale_01(people[:, 0])
scaled_weight = scale_01(people[:, 1])

print(scaled_height)
print(scaled_weight)

[0. 0. 1.]
[0.75 0.   1.  ]


In [109]:
scaled_people = np.vstack([scaled_height, scaled_weight])
print(scaled_people)

[[0.   0.   1.  ]
 [0.75 0.   1.  ]]


In [110]:
scaled_people = scaled_people.T#trasposizione
print(scaled_people)

[[0.   0.75]
 [0.   0.  ]
 [1.   1.  ]]


In [111]:
#implementazione più compatta
scaled_people = (people - np.min(people, axis=0)) / (np.max(people, axis=0) - np.min(people, axis=0))
print(scaled_people)

[[0.   0.75]
 [0.   0.  ]
 [1.   1.  ]]


In [112]:
scaled_A, scaled_B, scaled_C = scaled_people
print(scaled_A)
print(scaled_B)
print(scaled_C)

[0.   0.75]
[0. 0.]
[1. 1.]


In [113]:
print(norm(scaled_A-scaled_B))
print(norm(scaled_A-scaled_C))

0.75
1.0307764064044151


7.4
---

In [1]:
from sklearn import datasets, neighbors
from sklearn.utils import shuffle
from sklearn.preprocessing import StandardScaler

#Carico il dataset
digits = datasets.load_digits()
X, y = digits['data'], digits['target']

#Separo train e test
X, y = shuffle(X, y, random_state=123)
X_tr, X_val, X_test = X[:50], X[50:100], X[100:150]
y_tr, y_val, y_test = y[:50], y[50:100], y[100:150]

#Scalo i dati
scaler = StandardScaler()
X_tr = scaler.fit_transform(X_tr)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

#Valuto accuratezza dei modelli sul set di validazione
for k in [1,2,3,5,10]:
    val_acc = neighbors.KNeighborsClassifier(n_neighbors=k).fit(X_tr, y_tr).score(X_val, y_val)
    print('Validation accuracy with k {}: {:.2f}'.format(k, val_acc))                  

Validation accuracy with k 1: 0.78
Validation accuracy with k 2: 0.76
Validation accuracy with k 3: 0.62
Validation accuracy with k 5: 0.66
Validation accuracy with k 10: 0.52


In [2]:
import numpy as np

#Rifitto su tutto il training set
best_model = neighbors.KNeighborsClassifier(n_neighbors=1).fit(np.vstack([X_tr, X_val]),
                                                               np.hstack([y_tr, y_val]))

#Valuto accuratezza del miglior modello sul test set
print('Test accuracy with selected k: {:.2f}'.format(best_model.score(X_test, y_test))) 

Test accuracy with selected k: 0.84


<script>
  $(document).ready(function(){
    $('div.back-to-top').hide();
    $('nav#menubar').hide();
    $('div.prompt').hide();
    $('.hidden-print').hide();
  });
</script>

<footer id="attribution" style="float:right; color:#999; background:#fff;">
Created with Jupyter, delivered by Fastly, rendered by Rackspace.
</footer>