3.1
---

In [1]:
heights = {}
heights['Mount Everest'] = 8858
heights['K2'] = 8611
heights['Kangchenjunga'] = 8586

for mountain, height in heights.items():
    print('{} è alta {}'.format(mountain, height))
    
for i, mountain in enumerate(sorted(heights.keys())):
    print('La montagna numero {} è {} ed è alta {}'.format(i+1, mountain, heights[mountain]))

Mount Everest è alta 8858
K2 è alta 8611
Kangchenjunga è alta 8586
La montagna numero 1 è K2 ed è alta 8611
La montagna numero 2 è Kangchenjunga ed è alta 8586
La montagna numero 3 è Mount Everest ed è alta 8858


3.2
---

In [6]:
mountains = []

mountains += [{'name':'Mount Everest', 'height':8858, 'country':'Nepal'}]
mountains += [{'name':'K2', 'height':8611, 'country':'Pakistan'}]
mountains += [{'name':'Kangchenjunga', 'height':8586, 'country':'Nepal'}]

for i, m in enumerate(mountains):
    print('La montagna numero {} è {}, è alta {} e si trova in {}'.format(i,
                                                                          m['name'],
                                                                          m['height'],
                                                                          m['country']))

La montagna numero 0 è Mount Everest, è alta 8858 e si trova in Nepal
La montagna numero 1 è K2, è alta 8611 e si trova in Pakistan
La montagna numero 2 è Kangchenjunga, è alta 8586 e si trova in Nepal


In [5]:
mountain_names = [m['name'] for m in mountains]
mountain_heights = [m['height'] for m in mountains]

heights = {}

for i,n in enumerate(mountain_names):
    heights[n] = mountain_heights[i]
    
print(heights)

{'Mount Everest': 8858, 'K2': 8611, 'Kangchenjunga': 8586}


4.1, 4.2
---

In [35]:
lst = [3,6,5,8,12]

for element in lst:
    if element**2 % 2 == 0 and element**2 % 3 == 0:
        print('Il quadrato di %d è %d, che è multiplo sia di 2 che di 3' % (element, element**2))
    elif element**2 % 2 == 0:
        print('Il quadrato di %d è %d, che è multiplo di 2 ma non di 3' % (element, element**2))
    elif element**2 % 3 == 0:
        print('Il quadrato di %d è %d, che è multiplo di 3 ma non di 2' % (element, element**2))
    else:
        print('Il quadrato di %d è %d, che non è multiplo né di 2 né di 3' %  (element, element**2))
        
print('\n*******************\n')

multiples_of_2 = [element**2 for element in lst if element**2 % 2 == 0]
multiples_of_3 = [element**2 for element in lst if element**2 % 3 == 0]
multiples_of_2_and_not_of_3 = [element**2 for element in lst if element**2 % 2 == 0 and not element**2 % 3 == 0]

print(multiples_of_2)
print(multiples_of_3)
print(multiples_of_2_and_not_of_3)

Il quadrato di 3 è 9, che è multiplo di 3 ma non di 2
Il quadrato di 6 è 36, che è multiplo sia di 2 che di 3
Il quadrato di 5 è 25, che non è multiplo né di 2 né di 3
Il quadrato di 8 è 64, che è multiplo di 2 ma non di 3
Il quadrato di 12 è 144, che è multiplo sia di 2 che di 3

*******************

[36, 64, 144]
[9, 36, 144]
[64]


5.1, 5.2, 5.3
---

In [13]:
def show_user_info(user):
    print('\nNome:', user['name'])
    print('Età:', user['age'])
    print('Sesso:', user['sex'])

def show_all_users_by_age(users):
    for s in sorted(users, key = lambda x : x['age']):
        show_user_info(s)
        
def show_all_users_by_field(users, field='name'):
    for s in sorted(users, key = lambda x : x[field]):
        show_user_info(s)
        
def show_names_alphabetically(users):
    for name in sorted([u['name'] for u in users]):
        print(name)
    
francesco = {'name':'Francesco', 'age':30, 'sex':'M'}
giovanni = {'name':'Giovanni', 'age':68, 'sex':'M'}
elisa = {'name':'Elisa', 'age':27, 'sex':'F'}
michael = {'name':'Michael', 'age':30, 'sex':'M'}

users = [francesco, giovanni, elisa, michael]

print('Lista utenti per età:')
show_all_users_by_age(users)
print('\n*****************************')

print('\nLista utenti per età:')
show_all_users_by_field(users, field='age')
print('\n*****************************')

print('\nLista utenti per nome:')
show_all_users_by_field(users)
print('\n*****************************')

print('\nLista dei nomi degli utenti in ordine alfabetico:\n')
show_names_alphabetically(users)

Lista utenti per età:

Nome: Elisa
Età: 27
Sesso: F

Nome: Francesco
Età: 30
Sesso: M

Nome: Michael
Età: 30
Sesso: M

Nome: Giovanni
Età: 68
Sesso: M

*****************************

Lista utenti per età:

Nome: Elisa
Età: 27
Sesso: F

Nome: Francesco
Età: 30
Sesso: M

Nome: Michael
Età: 30
Sesso: M

Nome: Giovanni
Età: 68
Sesso: M

*****************************

Lista utenti per nome:

Nome: Elisa
Età: 27
Sesso: F

Nome: Francesco
Età: 30
Sesso: M

Nome: Giovanni
Età: 68
Sesso: M

Nome: Michael
Età: 30
Sesso: M

*****************************

Lista dei nomi degli utenti in ordine alfabetico:

Elisa
Francesco
Giovanni
Michael


5.4, 5.5
---

In [29]:
def is_adult(user):
    return user['age'] >= 18

def show_and_add_if_adult(user, db):
    show_user_info(user)
    #5.4
    #return db + [user] if user['age'] >= 18 else db
    #5.5
    return db + [user] if is_adult(user) else db

adult_users = []#database

print('\nTutti gli utenti:')
adult_users = show_and_add_if_adult({'name':'Francesco', 'age':30, 'sex':'M'}, adult_users)
adult_users = show_and_add_if_adult({'name':'Giovanni', 'age':68, 'sex':'M'}, adult_users)
adult_users = show_and_add_if_adult({'name':'Giulia', 'age':16, 'sex':'F'}, adult_users)
print('\n*****************************')

print('\nUtenti maggiorenni:')
for a in adult_users : show_user_info(a)


Tutti gli utenti:

Nome: Francesco
Età: 30
Sesso: M

Nome: Giovanni
Età: 68
Sesso: M

Nome: Giulia
Età: 16
Sesso: F

*****************************

Utenti maggiorenni:

Nome: Francesco
Età: 30
Sesso: M

Nome: Giovanni
Età: 68
Sesso: M


6.2
---

In [6]:
import numpy as np
import numpy.random as rdm
from math import sqrt

def py_std(X):
    X_mean = sum(X) / len(X)
    return sqrt(sum((x-X_mean)**2 for x in X) / len(X))

large_array = rdm.normal(size=(1000000,))

print(py_std(large_array))
print(np.std(large_array))
%timeit py_std(large_array)
%timeit np.std(large_array)

1.0003876317476104
1.0003876317476064
449 ms ± 44.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.33 ms ± 140 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


6.3
---

In [11]:
import numpy as np
import numpy.random as rdm

n_frames = 50
n_pixel_x = 5
n_pixel_y = 5
movie = rdm.randint(256, size=(n_frames, n_pixel_x, n_pixel_y))
print(movie)

[[[ 67  80  78 240 215]
  [ 17 200 175  31   7]
  [245 187 193 217  28]
  [ 22 203  25  27 186]
  [168  53  57 166 223]]

 [[141  64 197 184 255]
  [252  93 243  23 190]
  [ 44  92 113 207 116]
  [163  93 234  79 249]
  [ 42 148  69 142  82]]

 [[ 46  60  70  39 149]
  [194 178  28 162   9]
  [ 15  66  66  59  60]
  [231  31 127 247 145]
  [169 146  64 125  56]]

 ...

 [[101  97   8  99  54]
  [109 211 255   1 238]
  [177 246 166 174 206]
  [210 220 114 233  83]
  [126 250 209 249 228]]

 [[ 95  13 199 201 253]
  [246 154 247  57 220]
  [141 125  60 114 192]
  [ 32  15 151 138 154]
  [ 37 164   6  90 224]]

 [[107  77  89  81  96]
  [ 97 216 223  35 252]
  [115 147 225  78 180]
  [ 50 123 244 176 126]
  [213 189  79 221 167]]]


In [12]:
print(movie.shape)

(50, 5, 5)


In [15]:
pixel_mean_intensity = np.mean(movie, axis=0)
print(pixel_mean_intensity)
print(pixel_mean_intensity.shape)

[[123.62 122.18 117.36 131.26 132.34]
 [142.9  131.44 157.54 108.34 127.12]
 [146.64 134.38 134.8  151.32 146.64]
 [123.36 129.98 143.12 134.2  125.8 ]
 [115.86 128.66 135.16 129.18 139.58]]
(5, 5)


<script>
  $(document).ready(function(){
    $('div.back-to-top').hide();
    $('nav#menubar').hide();
    $('div.prompt').hide();
    $('.hidden-print').hide();
  });
</script>

<footer id="attribution" style="float:right; color:#999; background:#fff;">
Created with Jupyter, delivered by Fastly, rendered by Rackspace.
</footer>