3.4
---

In [1]:
numbers = [10, 2, 4, 8, 1.7]
squared_numbers = []

for i, x in enumerate(numbers):
    print('Il numero in posizione {} è {}'.format(i, x))
    squared_numbers += [x**2]
    
squared_numbers

Il numero in posizione 0 è 10
Il numero in posizione 1 è 2
Il numero in posizione 2 è 4
Il numero in posizione 3 è 8
Il numero in posizione 4 è 1.7


[100, 4, 16, 64, 2.8899999999999997]

3.5
---

In [2]:
names = ['francesco', 'elisa', 'alessandro', 'giovanni', 'maria teresa']
indexed_sorted_names = [[i, n] for i, n in enumerate(sorted(names))]

indexed_sorted_names

[[0, 'alessandro'],
 [1, 'elisa'],
 [2, 'francesco'],
 [3, 'giovanni'],
 [4, 'maria teresa']]

3.6
---

In [3]:
numbers = [10, 2, 4, 8, 1.7]
squared_numbers = [x**2 for x in numbers]

squared_numbers

[100, 4, 16, 64, 2.8899999999999997]

4.1, 4.2
---

In [4]:
lst = [3,6,5,8,12]

for element in lst:
    if element**2 % 2 == 0 and element**2 % 3 == 0:
        print('Il quadrato di {} è {}, che è multiplo sia di 2 che di 3'.format(element, element**2))
    elif element**2 % 2 == 0:
        print('Il quadrato di {} è {}, che è multiplo di 2 ma non di 3'.format(element, element**2))
    elif element**2 % 3 == 0:
        print('Il quadrato di {} è {}, che è multiplo di 3 ma non di 2'.format(element, element**2))
    else:
        print('Il quadrato di {} è {}, che non è multiplo né di 2 né di 3'.format(element, element**2))
        
print('\n**************************************************************\n')

multiples_of_2 = [element**2 for element in lst if element**2 % 2 == 0]
multiples_of_3 = [element**2 for element in lst if element**2 % 3 == 0]
multiples_of_2_and_not_of_3 = [element**2 for element in lst if element**2 % 2 == 0 and not element**2 % 3 == 0]

print(multiples_of_2)
print(multiples_of_3)
print(multiples_of_2_and_not_of_3)

Il quadrato di 3 è 9, che è multiplo di 3 ma non di 2
Il quadrato di 6 è 36, che è multiplo sia di 2 che di 3
Il quadrato di 5 è 25, che non è multiplo né di 2 né di 3
Il quadrato di 8 è 64, che è multiplo di 2 ma non di 3
Il quadrato di 12 è 144, che è multiplo sia di 2 che di 3

**************************************************************

[36, 64, 144]
[9, 36, 144]
[64]


5.1
---

In [5]:
heights = {}
heights['Mount Everest'] = 8858
heights['K2'] = 8611
heights['Kangchenjunga'] = 8586

for mountain, height in heights.items():
    print('{} è alta {}'.format(mountain, height))
    
for i, mountain in enumerate(sorted(heights.keys())):
    print('La montagna numero {} è {} ed è alta {}'.format(i+1, mountain, heights[mountain]))

Mount Everest è alta 8858
K2 è alta 8611
Kangchenjunga è alta 8586
La montagna numero 1 è K2 ed è alta 8611
La montagna numero 2 è Kangchenjunga ed è alta 8586
La montagna numero 3 è Mount Everest ed è alta 8858


5.2
---

In [6]:
mountains = []

mountains += [{'name':'Mount Everest', 'height':8858, 'country':'Nepal'}]
mountains += [{'name':'K2', 'height':8611, 'country':'Pakistan'}]
mountains += [{'name':'Kangchenjunga', 'height':8586, 'country':'Nepal'}]

for i, m in enumerate(mountains):
    print('La montagna numero {} è {}, è alta {} e si trova in {}'.format(i,
                                                                          m['name'],
                                                                          m['height'],
                                                                          m['country']))

La montagna numero 0 è Mount Everest, è alta 8858 e si trova in Nepal
La montagna numero 1 è K2, è alta 8611 e si trova in Pakistan
La montagna numero 2 è Kangchenjunga, è alta 8586 e si trova in Nepal


In [7]:
mountain_names = [m['name'] for m in mountains]
mountain_heights = [m['height'] for m in mountains]

heights = {}

for i,n in enumerate(mountain_names):
    heights[n] = mountain_heights[i]
    
print(heights)

{'Mount Everest': 8858, 'K2': 8611, 'Kangchenjunga': 8586}


5.3
---

In [8]:
def show_estate_info(e):
    print('Paese: {}'.format(e['country']))
    print('Estensione (mq): {}'.format(e['extension']))
    print('Terreno annesso?: {}'.format('Sì' if e['has_land'] else 'No'))
    print('Prezzo: {}K Euro'.format(e['price']))

In [9]:
estates = []

e1 = {'country':'Italia',    'extension':2000,  'has_land':False, 'price':10}
e2 = {'country':'Spagna',    'extension':12000, 'has_land':False, 'price':125}
e3 = {'country':'Argentina', 'extension':50000, 'has_land':True,  'price':300}

estates += [e1, e2, e3]

for i, e in enumerate(estates):
    print(f'\nImmobile #{i}')#sintassi alternativa a format, disponibile da Python 3.6
    show_estate_info(e)


Immobile #0
Paese: Italia
Estensione (mq): 2000
Terreno annesso?: No
Prezzo: 10K Euro

Immobile #1
Paese: Spagna
Estensione (mq): 12000
Terreno annesso?: No
Prezzo: 125K Euro

Immobile #2
Paese: Argentina
Estensione (mq): 50000
Terreno annesso?: Sì
Prezzo: 300K Euro


6.2
---

In [1]:
import numpy as np
import numpy.random as rdm
from math import sqrt

def py_std(x):
    mean_val = sum(x) / len(x)
    return sqrt(sum((val-mean_val)**2 for val in x) / len(x))

large_array = rdm.normal(size=(1000000,))

print(py_std(large_array))
print(np.std(large_array))

#confronto tempi di esecuzione
%timeit py_std(large_array)
%timeit np.std(large_array)

1.000504541252011
1.0005045412519882
299 ms ± 19.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.5 ms ± 97 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


6.3
---

In [2]:
import numpy as np
import numpy.random as rdm

n_frames = 50
n_pixel_y = 5
n_pixel_x = 5
movie = rdm.randint(0, 256, (n_frames, n_pixel_y, n_pixel_x))
print(movie)

[[[ 11 252 220  65  34]
  [  0  92 167 200 119]
  [124  14 134 246 229]
  [237 216  71 177 201]
  [ 13 245 111 145 223]]

 [[169  16 191 139 123]
  [166 153  21 172  56]
  [ 19  73 233 130 252]
  [ 98 164  31 186  16]
  [ 98  42  55  92 140]]

 [[ 63  24 124 186 243]
  [138  20 204 144 223]
  [ 74 121 155 240 103]
  [ 23 213   6 247  79]
  [239 185  50  44 246]]

 ...

 [[233 158 169 253  45]
  [225  78 229  71 195]
  [158 128 141 107 144]
  [ 95 208 204  67 118]
  [ 54 118  33 133 168]]

 [[  1 197 134  52 154]
  [ 46  22 108 204 246]
  [ 81 170 114  38  40]
  [  4 134 214 196 239]
  [106 208 196 164   9]]

 [[193  47 137 244  18]
  [100 127   0 138 216]
  [  2  12  17 232  97]
  [ 49  10 235  70 104]
  [242  96 246 141 159]]]


In [3]:
print(movie.shape)

(50, 5, 5)


In [4]:
pixel_mean_intensity = np.mean(movie, axis=0)
print(pixel_mean_intensity)
print(pixel_mean_intensity.shape)

[[105.16 130.16 119.34 124.02 130.1 ]
 [133.68 106.48 129.14 137.9  142.58]
 [113.28 132.   121.88 144.36 133.22]
 [121.46 137.04 127.08 131.62 123.52]
 [144.78 123.32 127.24 121.22 125.36]]
(5, 5)


6.4
---

In [5]:
import numpy as np
import numpy.random as rdm

values = rdm.normal(5, 3, 1000000)

#sottraggo 5 e guardo se ha funzionato
print(round(np.mean(values), 4))
values -= 5
print(round(np.mean(values), 4))

#implemento deviazione std e confronto con np.std
residuals = values - np.mean(values)
squared_residuals = residuals**2
variance = np.sum(squared_residuals) / values.size
print(np.std(values), np.sqrt(variance))

5.0001
0.0001
3.004073163065538 3.004073163065538


6.5
---

In [6]:
import numpy as np

X_train = np.array([[1,2,3],
                    [0,2,-1],
                    [-1,2,3],
                    [3,1,3]])

x_new = np.array([1,1,2])

y_train = np.array([0,1,0,1])

print(X_train)
print(y_train)
print(x_new)

[[ 1  2  3]
 [ 0  2 -1]
 [-1  2  3]
 [ 3  1  3]]
[0 1 0 1]
[1 1 2]


In [7]:
distances = [np.sqrt(np.sum((x - x_new) ** 2)) for x in X_train]#riga per riga
distances = np.round(distances, 1)
print(distances)

[1.4 3.3 2.4 2.2]


Posso calcolare le distanze in modo ancora più compatto. Definita la *Norma* di un vettore $d$-dimensionale,

$$\|x\|_2 := \sqrt{\sum_{i=1}^d x_i^2},$$

si può dire che la distanza euclidea tra due vettori $x$ e $x'$ è la norma del *vettore differenza* $x - x'$:

$$D(x, x') = \sqrt{\sum_{i=1}^{d}(x_i-x'_i)^2} = \|x - x'\|_2.$$

Proviamo intanto ad operare vettorialmente.

In [8]:
X_train - x_new#vettori differenza

array([[ 0,  1,  1],
       [-1,  1, -3],
       [-2,  1,  1],
       [ 2,  0,  1]])

In [9]:
(X_train - x_new) ** 2#differenze al quadrato

array([[0, 1, 1],
       [1, 1, 9],
       [4, 1, 1],
       [4, 0, 1]])

In [10]:
np.sum((X_train - x_new) ** 2, axis=1)#somma (lungo le colonne) degli scarti al quadrato

array([ 2, 11,  6,  5])

In [11]:
distances = np.sqrt(np.sum((X_train - x_new) ** 2, axis=1))#tutto vettoriale
distances = np.round(distances, 1)
print(distances)

[1.4 3.3 2.4 2.2]


Volendo, tutto in una riga:

In [12]:
print(np.round(np.sqrt(np.sum((X_train - x_new) ** 2, axis=1)), 1))

[1.4 3.3 2.4 2.2]


Adesso utilizziamo la funzione *norm* di numpy.

In [13]:
from numpy.linalg import norm

vec = np.random.random((5,))
print(vec)
print(np.sqrt(np.sum(vec**2)))
print(norm(vec))

[0.50936559 0.99728408 0.11055377 0.34465345 0.23877203]
1.2008534738099808
1.2008534738099808


In [14]:
print(np.round(norm(X_train - x_new, axis=1), 1))#utilizzando la norma vettorialmente

[1.4 3.3 2.4 2.2]


**Nota**: abbiamo smesso di scrivere cicli for!

6.6
---

In [15]:
people = np.array([[1.60, 66],
                   [1.60, 63],
                   [1.90, 67]])

print(people)

[[ 1.6 66. ]
 [ 1.6 63. ]
 [ 1.9 67. ]]


In [16]:
A, B, C = people
print(A)
print(B)
print(C)

[ 1.6 66. ]
[ 1.6 63. ]
[ 1.9 67. ]


In [17]:
print(norm(A-B))
print(norm(A-C))

3.0
1.0440306508910548


In [18]:
def scale_01(column):
    return (column - np.min(column)) / (np.max(column) - np.min(column))

scaled_height = scale_01(people[:, 0])
scaled_weight = scale_01(people[:, 1])

print(scaled_height)
print(scaled_weight)

[0. 0. 1.]
[0.75 0.   1.  ]


In [19]:
scaled_people = np.vstack([scaled_height, scaled_weight])
print(scaled_people)

[[0.   0.   1.  ]
 [0.75 0.   1.  ]]


In [20]:
scaled_people = scaled_people.T#trasposizione
print(scaled_people)

[[0.   0.75]
 [0.   0.  ]
 [1.   1.  ]]


Scriviamo tutto in modo più veloce e compatto, utilizzando il calcolo vettoriale.

In [21]:
print(people)

[[ 1.6 66. ]
 [ 1.6 63. ]
 [ 1.9 67. ]]


In [22]:
print(np.min(people, axis=0))#minimo per colonna (cioè, 'lungo le righe')

[ 1.6 63. ]


In [23]:
print(people - np.min(people, axis=0))

[[0.  3. ]
 [0.  0. ]
 [0.3 4. ]]


In [24]:
print(np.max(people, axis=0) - np.min(people, axis=0))

[0.3 4. ]


In [25]:
scaled_people = (people - np.min(people, axis=0)) / (np.max(people, axis=0) - np.min(people, axis=0))
print(scaled_people)

[[0.   0.75]
 [0.   0.  ]
 [1.   1.  ]]


In [26]:
scaled_A, scaled_B, scaled_C = scaled_people
print(scaled_A)
print(scaled_B)
print(scaled_C)

[0.   0.75]
[0. 0.]
[1. 1.]


In [27]:
print(norm(scaled_A-scaled_B))
print(norm(scaled_A-scaled_C))

0.75
1.0307764064044151


6.7
---

In [28]:
import numpy as np
from numpy.linalg import norm

np.random.seed(0)#fisso il generatore casuale per la riproducibilità dell'esperimento

def KNN(k, X, y, x):
    distances = norm(X - x, axis=1)
    sorted_labels = y[distances.argsort()]
    return np.argmax(np.bincount(sorted_labels[:k]))

def one_line_KNN(k, X, y, x):
    return np.argmax(np.bincount(y[norm(X - x, axis=1).argsort()][:k]))

X_train = np.random.random((7,4))
y_train = np.random.randint(0, 2, (7))
x_new = np.random.random((4,))

print('Matrice delle feature:\n', X_train)

print('\nVettore delle etichette:', y_train)

print('\nNuovo esempio da classificare:', x_new)

print('\nPredizione (k=3):', one_line_KNN(3, X_train, y_train, x_new))
print('Predizione (k=5):', one_line_KNN(5, X_train, y_train, x_new))

Matrice delle feature:
 [[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]
 [0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918]
 [0.11827443 0.63992102 0.14335329 0.94466892]]

Vettore delle etichette: [1 0 0 1 1 0 1]

Nuovo esempio da classificare: [0.73691818 0.21655035 0.13521817 0.32414101]

Predizione (k=3): 1
Predizione (k=5): 0


7.3
---

In [38]:
#Importo librerie
from sklearn import datasets, neighbors
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsRegressor as KNN
from sklearn.metrics import mean_absolute_error

#Carico il dataset
boston = datasets.load_boston()
X, y = boston['data'], boston['target']

print(boston['DESCR'])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [39]:
#Scalo le feature tra 0 e 1
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

#Separo train e test
X, y = shuffle(X, y, random_state=0)
X_train, X_test = X[:400], X[400:]
y_train, y_test = y[:400], y[400:]

#Addestro il modello
model = KNN(n_neighbors=3).fit(X_train, y_train)

#Ottengo predizioni e valuto il mae
predictions = model.predict(X_test)
mae = mean_absolute_error(y_test, predictions)
print('Model MAE on test set: {:.3f}'.format(mae))

Model MAE on test set: 2.845


7.4
---

In [40]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import MinMaxScaler
from sklearn.utils import shuffle
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.metrics import accuracy_score
import numpy as np

#Carico il dataset
iris = load_iris()
X, y = iris['data'], iris['target']

#Scalo le feature tra 0 e 1
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

#Separo train , validation e test
X, y = shuffle(X, y, random_state=123)
X_tr, X_val, X_test = X[:75], X[75:100], X[100:]
y_tr, y_val, y_test = y[:75], y[75:100], y[100:]

print(X_tr.shape, X_val.shape, X_test.shape)

(75, 4) (25, 4) (50, 4)


In [41]:
for k in [1,2,3,5,10]:
    model = KNN(n_neighbors=k)
    model.fit(X_tr, y_tr)
    predictions = model.predict(X_val)
    validation_accuracy = accuracy_score(y_val, predictions)
    print('Validation accuracy with k {}: {:.2f}'.format(k, validation_accuracy))   

Validation accuracy with k 1: 0.92
Validation accuracy with k 2: 0.96
Validation accuracy with k 3: 0.92
Validation accuracy with k 5: 0.92
Validation accuracy with k 10: 0.92


In [42]:
X_train = np.vstack([X_tr, X_val])
y_train = np.hstack([y_tr, y_val])

print(X_train.shape, y_train.shape)

(100, 4) (100,)


In [43]:
predictions = KNN(n_neighbors=2).fit(X_train, y_train).predict(X_test)
print('Test accuracy:', accuracy_score(y_test, predictions))

Test accuracy: 0.96


In questo caso utilizzare tutti i dati del training set per il test finale non ha migliorato l'accuratezza del modello.

8.1
---

In [44]:
import pandas as pd

df = pd.read_csv('data/titanic.csv', index_col='PassengerId')
df.rename(columns={'Sex':'Gender'}, inplace=True)

df['Name']

PassengerId
1                                Braund, Mr. Owen Harris
2      Cumings, Mrs. John Bradley (Florence Briggs Th...
3                                 Heikkinen, Miss. Laina
4           Futrelle, Mrs. Jacques Heath (Lily May Peel)
5                               Allen, Mr. William Henry
                             ...                        
887                                Montvila, Rev. Juozas
888                         Graham, Miss. Margaret Edith
889             Johnston, Miss. Catherine Helen "Carrie"
890                                Behr, Mr. Karl Howell
891                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [45]:
df['Name'].iloc[0]

'Braund, Mr. Owen Harris'

In [46]:
name = df['Name'].iloc[0]

In [47]:
name

'Braund, Mr. Owen Harris'

In [48]:
name.index(',')

6

In [49]:
name[name.index(',')]

','

In [50]:
name[name.index(',') + 2]

'M'

In [51]:
name.index('.')

10

In [52]:
name[name.index(',') + 2 : name.index('.')]

'Mr'

In [53]:
df['Name'].apply(lambda name: name[name.index(',') + 2 : name.index('.')])

PassengerId
1        Mr
2       Mrs
3      Miss
4       Mrs
5        Mr
       ... 
887     Rev
888    Miss
889    Miss
890      Mr
891      Mr
Name: Name, Length: 891, dtype: object

In [54]:
df['Title'] = df['Name'].apply(lambda name: name[name.index(',') + 2 : name.index('.')])

In [55]:
df[['Name', 'Title']].head(20)

Name   Title
PassengerId                                                           
1                                      Braund, Mr. Owen Harris      Mr
2            Cumings, Mrs. John Bradley (Florence Briggs Th...     Mrs
3                                       Heikkinen, Miss. Laina    Miss
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)     Mrs
5                                     Allen, Mr. William Henry      Mr
6                                             Moran, Mr. James      Mr
7                                      McCarthy, Mr. Timothy J      Mr
8                               Palsson, Master. Gosta Leonard  Master
9            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)     Mrs
10                         Nasser, Mrs. Nicholas (Adele Achem)     Mrs
11                             Sandstrom, Miss. Marguerite Rut    Miss
12                                    Bonnell, Miss. Elizabeth    Miss
13                              Saundercock, Mr. William Henry      Mr
14                                 Andersson, Mr. Anders Johan      Mr
15                        Vestrom, Miss. Hulda Amanda Adolfina    Miss
16                            Hewlett, Mrs. (Mary D Kingcome)      Mrs
17                                        Rice, Master. Eugene  Master
18                                Williams, Mr. Charles Eugene      Mr
19           Vander Planke, Mrs. Julius (Emelia Maria Vande...     Mrs
20                                     Masselmani, Mrs. Fatima     Mrs

In [56]:
df.Title.value_counts()

Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Mlle              2
Col               2
Major             2
Jonkheer          1
Ms                1
Lady              1
Don               1
Capt              1
Mme               1
Sir               1
the Countess      1
Name: Title, dtype: int64

In [57]:
df[df.Title == "the Countess"]#.Survived

Survived  Pclass  \
PassengerId                     
760                 1       1   

                                                          Name  Gender   Age  \
PassengerId                                                                    
760          Rothes, the Countess. of (Lucy Noel Martha Dye...  female  33.0   

             SibSp  Parch  Ticket  Fare Cabin Embarked         Title  
PassengerId                                                           
760              0      0  110152  86.5   B77        S  the Countess

8.2
---

Il modello $M_{gender}$ dice la cosa giusta quando:
- una femmina sopravvive
- un maschio muore.

Quindi, per calcolarne l'accuratezza, abbiamo bisogno
- della probabilità di essere femmina o maschio
- della probabilità di sopravvivenza delle femmine e dei maschi.

Come combinare questi quattro valori?

Contiamo per prima cosa i maschi e le femmine.

In [58]:
df.shape

(891, 12)

In [59]:
df.Gender.value_counts()

male      577
female    314
Name: Gender, dtype: int64

In [60]:
df.Gender.value_counts() / df.shape[0]

male      0.647587
female    0.352413
Name: Gender, dtype: float64

In [61]:
df.Gender.value_counts(normalize=True)

male      0.647587
female    0.352413
Name: Gender, dtype: float64

Adesso usiamo groupby per

- raggruppare i dati in base alla colonna *Gender*
- estrarre da entrambi i gruppi (femmine e maschi) la colonna *Survived*, sotto forma di Series di valori interi (0 o 1).

La media di ognuno di questi due vettori (uno per le femmine e uno per i maschi), sarà pari alla *probabilità di sopravvivenza* del rispettivo gruppo.

In [62]:
df.groupby('Gender')['Survived'].mean()

Gender
female    0.742038
male      0.188908
Name: Survived, dtype: float64

Tornando all'accuratezza del modello $M_{gender}$, questa sarà pari a:

$$P_{female} \cdot SP_{female} + P_{male} \cdot (1 - SP_{male})$$

In [63]:
is_female = (df.Gender == 'female')
is_male = (df.Gender == 'male')
survives = (df.Survived == 1)
dies = (df.Survived == 0)

In [64]:
a = len(df[is_female & survives])

a

233

In [65]:
b = len(df[is_male & dies])

b

468

In [66]:
(a + b) / len(df)

0.7867564534231201

In [67]:
P_male, P_female = df.Gender.value_counts(normalize=True)

P_male, P_female

(0.6475869809203143, 0.35241301907968575)

In [68]:
SP_female, SP_male = df.groupby('Gender')['Survived'].mean()

SP_female, SP_male

(0.7420382165605095, 0.18890814558058924)

In [69]:
P_female*SP_female + P_male*(1 - SP_male)

0.7867564534231202

8.3
---

In [70]:
aggregations = {'mean_age':pd.NamedAgg('Age', 'mean'),
                'most_frequent_title':pd.NamedAgg('Title', lambda t : t.mode()),
                'no_cabin_info':pd.NamedAgg('Cabin', lambda c : c.isna().sum() / c.size)}

df.groupby('Gender').agg(**aggregations)

mean_age most_frequent_title  no_cabin_info
Gender                                              
female  27.915709                Miss       0.691083
male    30.726645                  Mr       0.814558

<script>
  $(document).ready(function(){
    $('div.back-to-top').hide();
    $('nav#menubar').hide();
    $('div.prompt').hide();
    $('.hidden-print').hide();
  });
</script>

<footer id="attribution" style="float:right; color:#999; background:#fff;">
Created with Jupyter, delivered by Fastly, rendered by Rackspace.
</footer>